apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: https://github.com/norouzzadegan/argocd-demo.git
    targetRevision: main
    path: ./manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo

  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - Replace=false
      - ServerSideApply=false
  # syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true

    # syncOptions:
    #   - CreateNamespace=true