apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
  namespace: argocd-demo
spec:
  replicas: 8
  selector:
    matchLabels:
      app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
        - name: nginx
          image: jfrog.balout.co/all-docker/nginx:1.27
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
